[package]
name = "dbcrossbarlib"
version = "0.0.3"
authors = ["Eric Kidd <git@randomhacks.net>"]
build = "build.rs"
edition = "2018"

license = "(Apache-2.0 OR MIT)"

[build-dependencies]
peg = "0.5"

[dependencies]
bytes = "0.4.11"
csv = "1.0.5"
diesel = { version = "1.3.3", features = ["postgres"] }
failure = "0.1.2"
lazy_static = "1.2.0"
log = "0.4.5"
native-tls = "0.2.2"
postgres = { version = "0.15.2", features = ["with-native-tls"] }
rand = "0.6"
regex = "1.1.0"
serde = "1.0.79"
serde_json = "1.0.32"
serde_derive = "1.0.79"
slog = { version = "2.4.1", features = ["max_level_trace", "release_max_level_trace"] }
strum = "0.13.0"
strum_macros = "0.13.0"
tempdir = "0.3.7"
tokio = { version = "0.1", features = ["async-await-preview"] }
tokio-process = { version = "0.2" }
tokio-async-await = "0.1"
try_from = "0.3.2"
url = "1.7.1"
