[package]
name = "dbcrossbarlib"
version = "0.0.14-rc.2"
authors = ["Eric Kidd <git@randomhacks.net>"]
build = "build.rs"
edition = "2018"

description = "Library for copying data between databases (pre-release)"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/faradayio/dbcrossbar"
documentation = "https://docs.rs/dbcrossbarlib/"

[build-dependencies]
peg = "0.5"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.11"
cast = "0.2.2"
chrono = "0.4.6"
csv = "1.0.5"
diesel = { version = "1.3.3", features = ["postgres"] }
failure = "0.1.2"
geo-types = "0.4"
geojson = "0.15.0"
hex = "0.3.2"
lazy_static = "1.2.0"
log = "0.4.5"
native-tls = "0.2.2"
postgres = { version = "0.15.2", features = ["with-native-tls"] }
rand = "0.6"
regex = "1.1.0"
serde = "1.0.79"
serde_json = "1.0.32"
serde_derive = "1.0.79"
slog = "2.4.1"
strum = "0.15.0"
strum_macros = "0.15.0"
tempdir = "0.3.7"
# Lock exact versions to work around some nightly Rust breakage.
#
# See https://github.com/tokio-rs/tokio/issues/1042 for compatibility
# of tokio-async-await with nightly Rust.
tokio = { version = "=0.1.18", features = ["async-await-preview"] }
tokio-process = { version = "=0.2.3" }
tokio-async-await = "=0.1.6"
try_from = "0.3.2"
url = "1.7.1"
uuid = "0.6.5"
wkb = "0.4"
